### ISSUE TITLE
Get notified after file is fully written

### ISSUE THREAD

**Issue by rmvz3** [gurinderhans/SwiftFSWatcher#3]
Hi. I'm using your library and it's being very useful to me but there's something that it's keeping me from complete my project.

When I observe a folder for changes and I copy a file to the directory it turns that your library triggers its response block as soon as the file is being created. Since sometimes the file is copied from another drive or has a big size, when my app receives the event notification and try to modify the file, this is not fully copied and the changes are not done. I've observed that another event appears when the file is fully copied but I can't manage to filter the eventFlag to isolate it.

Is there a way to get the final event in a copy with your library? Any indication would be very appreciated.

Thank you very much.

R.M.

**Comment by gurinderhans** [comment]
Hi @rmvz3, the `eventFlag` is your best bet on filtering the two separate conditions. When copying a file into some folder, it does send two separate events, one at start of copying and another at end. I also noticed that the eventFlag isn't a consistent number that you can just compare to and get done with. I'm not 100% with how the `eventFlag`'s are created, as they seem to be always changing and not fully consistent. 

However, through my testing I found when copying starts the `eventFlag` is always `107776` and it only changes after copying done. If this is similar to what you might be getting then we can be sure this particular flag is consistent. So you can take that `eventFlag` as a signal of copying started, and once you receive the second event of the same file, you know copying has finished, and now you can start to modify your files.

I would try this first and see if it works, if it doesn't let me know and I can dig deeper to find something else.

**Comment by rmvz3** [comment]
Hi Gurinder.

After some experimentation I think I'm done. Since I'm only interested in the final event to be sure that any file modification is done, I ended with this (in Swift):

```
       `for ev in changeEvents
        {                
            // File ended copy or replace operations
            let flag = ev.eventFlag as Int
            if flag & kFSEventStreamEventFlagItemIsFile == kFSEventStreamEventFlagItemIsFile
            {
                if flag & kFSEventStreamEventFlagItemChangeOwner == kFSEventStreamEventFlagItemChangeOwner
                {
                     log.error("End of Copy operation: \(ev.eventPath)")
                }
                else
                {
                    if ((flag & kFSEventStreamEventFlagItemXattrMod == kFSEventStreamEventFlagItemXattrMod) &&
                        (flag & kFSEventStreamEventFlagItemChangeOwner != kFSEventStreamEventFlagItemChangeOwner) &&
                        (flag & kFSEventStreamEventFlagItemFinderInfoMod == kFSEventStreamEventFlagItemFinderInfoMod) &&
                        (flag & kFSEventStreamEventFlagItemModified == kFSEventStreamEventFlagItemModified) &&
                        (flag & kFSEventStreamEventFlagItemCreated != kFSEventStreamEventFlagItemCreated))
                    {
                        log.error("End of Move or Rename opertation: \(ev.eventPath)")
                    }
                }
            }`
```

I'm still testing operation combinations (different drives, renaming, replacing…) but it seems to work so far. Thank you very much for your code. It really helped me.

Best.

R,M.

**Comment by gurinderhans** [comment]
Ah interesting that you look for change owner flag to detect the end. And the event flags can get a bit messy when detecting complex operations such as this. Also the reason I didn't include it in the library itself.

Still, glad to see you solving your problem!
