### ISSUE TITLE
compatibility to swift 3.0.2

### ISSUE THREAD

**Issue by minafarid** [gurinderhans/SwiftFSWatcher#5]
It looks like I can't run the Framework on swift 3.0.2.
The code syntax is different, any hints on what needs to change?

**Comment by gurinderhans** [comment]
I will have a look soon, thanks for letting me know

**Comment by minafarid** [comment]
XCode migrated the code syntax to 3.0.2 but there was API differences.

**Comment by gurinderhans** [comment]
Closing this as master should be latest swift 3
